// Questions

const questions = [
    { text: "I honestly express my opinions, even if unpopular.", trait: "Honesty-Humility" },
    { text: "I pretend to like people to get what I want.", trait: "Honesty-Humility", reverse: true },
    { text: "It's important to follow rules.", trait: "Honesty-Humility" },
    { text: "I sometimes take advantage of others.", trait: "Honesty-Humility", reverse: true },
    { text: "I don't care about money too much.", trait: "Honesty-Humility" },
    { text: "I enjoy having things that others envy.", trait: "Honesty-Humility", reverse: true },
    { text: "New things scare me.", trait: "Emotionality" },
    { text: "I enjoy horror movies.", trait: "Emotionality", reverse: true },
    { text: "I worry a lot about making mistakes.", trait: "Emotionality" },
    { text: "Thinking of the future makes me anxious.", trait: "Emotionality" },
    { text: "I ask for advice to make decisions.", trait: "Emotionality" },
    { text: "I don't like confrontation.", trait: "Emotionality" },
    { text: "I feel confident when interacting with people.", trait: "Extraversion" },
    { text: "I am naturally outgoing.", trait: "Extraversion" },
    { text: "I like talking in large groups of people.", trait: "Extraversion" },
    { text: "I take the lead in group situations.", trait: "Extraversion" },
    { text: "I am the life of the party.", trait: "Extraversion" },
    { text: "I feel energetic when around friends.", trait: "Extraversion" },
    { text: "I forgive people easily.", trait: "Agreeableness" },
    { text: "I hold grudges for a long time.", trait: "Agreeableness", reverse: true },
    { text: "I avoid confrontations.", trait: "Agreeableness" },
    { text: "I am sometimes harsh with people.", trait: "Agreeableness", reverse: true },
    { text: "I compromise to make others happy.", trait: "Agreeableness" },
    { text: "I insist on having things my own way.", trait: "Agreeableness", reverse: true  },
    { text: "I am organized.", trait: "Conscientiousness" },
    { text: "I plan my day.", trait: "Conscientiousness" },
    { text: "I follow through on my commitments.", trait: "Conscientiousness" },
    { text: "I strive to do the best at work.", trait: "Conscientiousness" },
    { text: "I double-check my work.", trait: "Conscientiousness" },
    { text: "I am meticulous.", trait: "Conscientiousness" },
    { text: "I like artsy events.", trait: "Openness to Experience" },
    { text: "Nature is important to me.", trait: "Openness to Experience" },
    { text: "I like solving puzzles and riddles.", trait: "Openness to Experience" },
    { text: "I like learning new things.", trait: "Openness to Experience" },
    { text: "I like to come up with new ideas.", trait: "Openness to Experience" },
    { text: "I have a vivid imagination.", trait: "Openness to Experience" },
];

export default questions;